apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: my-producer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
# Remove following # at "5. Authorize Connections"
#  authorization:
#    type: simple
#    acls:
#      - resource:
#          type: topic
#          name: my-topic
#        operation: Write
#      - resource:
#          type: topic
#          name: my-topic
#        operation: Describe
